name: visionlog
description: A dream journal app.

publish_to: 'none'

version: 4.0.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.0.0+4
  intl: ^0.17.0
  url_launcher: ^6.0.17
  charts_flutter: ^0.12.0

  cupertino_icons: ^1.0.0
  google_sign_in: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

