name: visionlog
description: A dream journal app.

publish_to: 'none'

version: 2.0.0+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.0.0+4
  intl: ^0.17.0
  url_launcher: ^6.0.17
  charts_flutter: ^0.12.0

  cupertino_icons: ^1.0.0
  google_sign_in: ^5.2.1
  firebase_auth: ^3.3.0
  font_awesome_flutter: ^9.2.0
  provider: ^6.0.1
  flutter_svg: ^1.0.0
  cloud_firestore: ^3.1.1
  package_info_plus: ^1.3.0
  in_app_purchase: ^2.0.1
  csv: ^5.0.1
  ext_storage:
    git:
      url: git://github.com/GitJournal/ext_storage.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

